// signup.tsx

import { Metadata } from "next";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

function SignupPage() {
  return (
    <div className="w-full max-w-md bg-card text-foreground rounded-lg drop-shadow-xl p-8">
      <h1 className="text-3xl font-bold mb-4 text-primary">
        Create an Account
      </h1>
      <form>
        <div className="mb-4">
          <label htmlFor="username" className="block mb-2 text-sm font-medium">
            Username/Email address
          </label>
          <input
            id="username"
            type="text"
            className="w-full rounded-md border  shadow-sm px-3 py-2"
          />
        </div>
        <div className="mb-4">
          <label htmlFor="password" className="block mb-2 text-sm font-medium">
            Password
          </label>
          <input
            id="password"
            type="password"
            className="w-full rounded-md border  shadow-sm px-3 py-2"
          />
        </div>
        <div className="mb-4">
          <label
            htmlFor="confirmPassword"
            className="block mb-2 text-sm font-medium"
          >
            Confirm Password
          </label>
          <input
            id="confirmPassword"
            type="password"
            className="w-full rounded-md border  shadow-sm px-3 py-2"
          />
        </div>
        <button
          type="submit"
          className="w-full rounded-md bg-primary text-primary-foreground py-2 px-4 shadow-md hover:scale-95 transition"
        >
          Sign Up
        </button>
      </form>
      <p className="mt-4 text-sm text-gray-500">
        Already have an account?{" "}
        <Link href="/login" className="text-primary hover:underline">
          Log in
        </Link>
      </p>
    </div>
  );
}

export default SignupPage;
